### ISSUE TITLE
Generates invalid functions? 

### ISSUE THREAD

**Issue by nabati** [ajv-validator/ajv-errors#96]
Hi!

I've tried including everything that is needed to resolve this. Let me know if something is missing or if I can help!

Code:

JSON-Schema
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$async": true,
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "errorMessage": "this is an error message"
    }
  }
}
```

Code
```
  const ajv = new Ajv({ allErrors: true });
  ajvErrors(ajv);
  ajv.addSchema(TEST_SCHEMA, "test");
  await ajv.validate('test', 'somedata');
```

Error: 
```
Error compiling schema, function code: const Error0 = scope.Error[0];const schema16 = scope.schema[10];return async function validate14(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;if(data && typeof data == "object" && !Array.isArray(data)){if(data.title !== undefined){if(typeof data.title !== "string"){const err0 = {instancePath:instancePath+"/title",schemaPath:"#/properties/title/type",keyword:"type",params:{type: "string"},message:"must be string"};if(vErrors === null){vErrors = [err0];}else {vErrors.push(err0);}errors++;}if(errors > 0){for(const err1 of vErrors){if((((({"str":"err1"}.keyword !== "errorMessage") && (!{"str":"err1"}.emUsed)) && (({"str":"err1"}.instancePath === instancePath+{"_items":["\"/title\""]}) || (({"str":"err1"}.instancePath.indexOf(instancePath+{"_items":["\"/title\""]}) === 0) && ({"str":"err1"}.instancePath[instancePath+{"_items":["\"/title\""]}.length] === "/")))) && ({"str":"err1"}.schemaPath.indexOf("#/properties/title") === 0)) && ({"str":"err1"}.schemaPath["#/properties/title".length] === "/")){{"str":"emErrs0"}.push({"str":"err1"});{"str":"err1"}.emUsed = true;}}if({"str":"emErrs0"}.length){if(vErrors === null){vErrors = [{"str":"err2"}];}else {vErrors.push({"str":"err2"});}errors++;}const emErrs1 = [];for(const err3 of vErrors){if(!{"str":"err3"}.emUsed){{"str":"emErrs1"}.push({"str":"err3"});}}vErrors = emErrs1;errors = {"str":"emErrs1"}.length;}}}else {const err4 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"};if(vErrors === null){vErrors = [err4];}else {vErrors.push(err4);}errors++;}if(errors === 0){return data;}else {throw new Error0(vErrors);}}

...

SyntaxError: Unexpected token ':'
```

Seems like some of the generated code is not correct? 

Particularly; these snippets which are repeated multiple times.:
```
{"str":"emErrs0"}.push({"str":"err1"});

// ...

{"str":"err1"}.emUsed = true;
``` 

Maybe it's something in my environment? 

Running node 14.16.0.
ajv 8.1.0
ajv-errors 3.0.0

Suggestions?

**Comment by nabati** [comment]
Running this in another repo, same version of the libraries as far as I can see, but getting a different result. Not sure what the issue could be 🤔 

```
async function validate14(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;if(data && typeof data == "object" && !Array.isArray(data)){if(data.title !== undefined){if(typeof data.title !== "string"){const err0 = {instancePath:instancePath+"/title",schemaPath:"#/properties/title/type",keyword:"type",params:{type: "string"},message:"must be string"};if(vErrors === null){vErrors = [err0];}else {vErrors.push(err0);}errors++;}if(errors > 0){const emErrs0 = [];for(const err1 of vErrors){if(((((err1.keyword !== "errorMessage") && (!err1.emUsed)) && ((err1.instancePath === instancePath+"/title") || ((err1.instancePath.indexOf(instancePath+"/title") === 0) && (err1.instancePath[instancePath+"/title".length] === "/")))) && (err1.schemaPath.indexOf("#/properties/title") === 0)) && (err1.schemaPath["#/properties/title".length] === "/")){emErrs0.push(err1);err1.emUsed = true;}}if(emErrs0.length){const err2 = {instancePath:instancePath+"/title",schemaPath:"#/properties/title/errorMessage",keyword:"errorMessage",params:{errors: emErrs0},message:"this is an error message"};if(vErrors === null){vErrors = [err2];}else {vErrors.push(err2);}errors++;}const emErrs1 = [];for(const err3 of vErrors){if(!err3.emUsed){emErrs1.push(err3);}}vErrors = emErrs1;errors = emErrs1.length;}}}else {const err4 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"};if(vErrors === null){vErrors = [err4];}else {vErrors.push(err4);}errors++;}if(errors === 0){return data;}else {throw new Error0(vErrors);}}
```

Relevant parts are translated to the following instead. 

```
emErrs0.push(err1);
err1.emUsed = true;
```

Any idea why this could be?

**Comment by nabati** [comment]
For the sake of future travellers:

I didn't pinpoint the exact root cause of this issue, but my best guess is that it was due to some dependency getting linked together in an incorrect way. 

We are using a mono repo setup, and adding `nohoist` to the root-most package.json resolved seems to have resolved this issue;

```
  "workspaces": {
    "packages": [
      "apps/*",
     ],
    "nohoist": ["**/ajv*", "**/ajv*/**"]
  },
```

**Comment by mtmacdonald** [comment]
I've seen this too. For me it happens when I've transpiled my ES6 usage with babel. 

```
/Users/mark/Dev/wellplan/node_modules/node-json-migrator/node_modules/ajv/dist/compile/index.js:121
        throw e;
        ^

SyntaxError: Unexpected token ':'
    at new Function (<anonymous>)
    at Ajv.compileSchema (/Users/mark/Dev/wellplan/node_modules/node-json-migrator/node_modules/ajv/lib/compile/index.ts:171:26)
    at Ajv._compileSchemaEnv (/Users/mark/Dev/wellplan/node_modules/node-json-migrator/node_modules/ajv/lib/core.ts:718:24)
    at Ajv.compile (/Users/mark/Dev/wellplan/node_modules/node-json-migrator/node_modules/ajv/lib/core.ts:370:34)
    at Object.<anonymous> (/Users/mark/Dev/wellplan/node_modules/node-json-migrator/dist/plan/plan.js:29:27)
```
